{{ if (eq .chezmoi.os "linux") }}

[".local/share/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
[".local/share/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
[".local/share/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/refs/heads/master.zip"
    exact = true
    stripComponents = 1
[".config/tmux/nord-tmux"]
    type = "archive"
    url = "https://github.com/arcticicestudio/nord-tmux/archive/master.zip"
    exact = true
    stripComponents = 1
{{ end }}

